version: '3'

services:
    jekyll:
        image: jekyll/jekyll:3.4.3
        command: jekyll serve
        container_name: jekyll-bpb
        restart: always
        volumes:
          - ./jekyll:/srv/jekyll
        ports:
          - "4000"
